create table catalogue
(
    id           int GENERATED BY DEFAULT AS IDENTITY(NO CACHE) primary key , -- auto_increment
    title        varchar(60) not null,
    description  varchar(80) not null,
    type         varchar(20) not null,
    price        decimal(19,4) not null,
    ingredients  varchar(120) not null,
    allergens    varchar(120),
    imageURL     varchar(60),
    weight       int not null,
    gluten_free  boolean not null,
    lactose_free boolean not null
);

create table users
(
    id       int GENERATED BY DEFAULT AS IDENTITY(NO CACHE) primary key,
    login    varchar(40) not null,
    password varchar(40) not null,
    unique uniq_login (login)
);

create table orders
(
    id         int GENERATED BY DEFAULT AS IDENTITY(NO CACHE) primary key,
    order_date datetime not null,
    login      varchar(40) not null,
    order_list text not null,
    order_cost decimal(19,4) not null
);

create table permissions
(
    id         int primary key auto_increment,
    permission varchar(30) not null,
    unique uniq_permission (permission)
);

create table user_to_permissions
(
    user_id       int not null,
    permission_id int not null,
    constraint fk_user_to_permission_user foreign key (user_id) references users (id),
    constraint fk_user_to_permission_permission foreign key (permission_id) references permissions (id)
);

create table user_to_products
(
    user_id    int          not null,
    product_id varchar(255) not null,
    quantity   int          not null,
    constraint fk_user_to_products_user foreign key (user_id) references users (id),
    constraint fk_user_to_product_id foreign key (product_id) references catalogue (id)
);

insert into permissions (permission)
values ('ADMIN');

insert into catalogue (title, description, type, price, ingredients, allergens, imageURL, weight, gluten_free, lactose_free)
values ('baguette authentic', 'Long, thin loaf of French bread that perfectly completes any meal.',      'BREAD',  2.0, 'wheat flour, water, yeast, salt', 'wheat flour',         'products-image/1.jpg', 150, true, true),
       ('Mary’s croissant',   'So special and regular at the same time. Give a taste of the divine.',    'PASTRY', 1.0, 'wheat flour, water, yeast, salt', 'wheat flour','products-image/2.jpg', 80, true, false),
       ('pain au chocolat',   'Puff dough along with a dark chocolate inside. Just as good as it gets.', 'PASTRY', 1.5, 'water, yeast, salt', null,         'products-image/3.jpg', 110, false, false);